# Generated by Django 2.2.6 on 2019-10-16 00:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerName', models.CharField(help_text='Insert Customer Name', max_length=200)),
                ('CustomerId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CustomerTel', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter Phone Number linked to Mobile Money +256--', max_length=128, region=None)),
                ('Location', models.CharField(default='Kampala', help_text='Insert Customer Location', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MomoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='', help_text='Insert Customer Mobile', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('external_id', models.CharField(default='', help_text='Insert Customer Mobile', max_length=15)),
                ('payee_note', models.CharField(default='', help_text='Insert Payee Note', max_length=200)),
                ('payer_message', models.CharField(default='', help_text='Insert Payment Message', max_length=200)),
                ('currency', models.CharField(default='', help_text='Insert Customer Mobile', max_length=3)),
                ('reqtyp', models.CharField(default='', help_text='Insert Request Type', max_length=200)),
                ('status', models.CharField(default='', help_text='Insert status', max_length=200)),
                ('transref', models.CharField(default='', help_text='Transaction Reference from MTN', max_length=200)),
                ('customername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momo.Customer')),
            ],
        ),
    ]
